site_name: Aarhus NLP
site_description: 'Natural Language Processing Group at Aarhus University'
repo_url: https://github.com/centre-for-humanities-computing/
nav:
  - Home: 
      About: index.md
      People: people.md
  - Research:
     - Publications: publications.md
     - Projects: projects.md
theme:
  name: material
  logo: images/logo.svg
  font:
    text: Merriweather Sans
  navigation_depth: 3
  palette:
    primary: 'white'
    accent: '#655a9f'
  features:
      - toc.integrate
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.indexes
      - toc.follow
      - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
